# Generated by Django 4.0.1 on 2022-10-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0026_alter_post_content_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_content',
            name='time_create',
            field=models.DateTimeField(default=1),
        ),
    ]
