# Generated by Django 4.0.1 on 2022-10-19 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newfeed', '0027_alter_post_content_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_content',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post_content',
            name='time_create',
            field=models.DateTimeField(),
        ),
    ]
