# Generated by Django 4.0.1 on 2022-10-19 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newfeed', '0029_alter_post_content_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_content',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_content_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='post_content',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_content_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
