# Generated by Django 4.0.1 on 2022-10-19 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0030_post_content_updated_by_alter_post_content_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_content',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 19, 11, 2, 21, 245407)),
        ),
    ]
