# Generated by Django 3.2.16 on 2022-11-11 03:48

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_comment',
            name='post',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, to='newfeed.post_content'),
        ),
    ]
