# Generated by Django 4.0.1 on 2022-10-01 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0002_remove_post_image_alter_post_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 3, 46, 58, 385867)),
        ),
    ]
