# Generated by Django 4.0.1 on 2022-10-01 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0003_alter_post_time_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('time_create', models.DateTimeField(default=datetime.datetime(2022, 10, 2, 3, 48, 23, 697544))),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
