# Generated by Django 4.0.1 on 2022-10-01 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0004_post_content_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_content',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 3, 49, 16, 641349)),
        ),
    ]
