# Generated by Django 4.0.1 on 2022-10-02 11:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0005_alter_post_content_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_content',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_content',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 18, 53, 49, 264186)),
        ),
    ]
