# Generated by Django 4.0.1 on 2022-10-02 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0006_post_content_image_alter_post_content_time_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_content',
            name='image',
        ),
        migrations.AlterField(
            model_name='post_content',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 21, 18, 56, 488540)),
        ),
    ]
