# Generated by Django 4.0.1 on 2022-10-02 14:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0007_remove_post_content_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_content',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_content',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 21, 24, 9, 451830)),
        ),
    ]
