# Generated by Django 4.0.1 on 2022-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0009_remove_post_content_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_content',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
