# Generated by Django 4.0.1 on 2022-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0010_alter_post_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_content',
            name='image',
            field=models.FileField(upload_to='image'),
        ),
    ]
