# Generated by Django 4.0.1 on 2022-10-05 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0014_alter_post_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_content',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
