# Generated by Django 4.0.1 on 2022-10-06 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newfeed', '0019_alter_post_content_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_content',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 40, 47, 722046)),
        ),
    ]
